### ISSUE TITLE
[1.7.10] Remove the mod that allows you to cross the leaves

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#309]

**Comment by quentin452** [comment]
fixed by deleting hardmodetweaks-1.1.4 in V0.32

**Comment by GamebP** [comment]
https://www.reddit.com/r/feedthebeast/comments/5ry5jy/is_there_a_mod_that_makes_tree_leaves_nonsolid/

> fixed by deleting hardmodetweaks-1.1.4 in V0.32
