### ISSUE TITLE
[1.7.10] Fps freeze when use "R" or "U" key to search recipes in NEI

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#342]
![Capture d’écran_2023-03-13_08-21-56](https://user-images.githubusercontent.com/42176772/224633656-106c7ac0-fcfb-42bd-a963-30dc229a2cf2.png)

**Comment by GamebP** [comment]
For an example: To get an items Light blue dye i press LETTER "R" to how to get the first product / or just single item.
But letter "U" is how to get recepies crafting block by block. 

I think you are lagging / or having fps freeze beacuse its checking any other possoble way to get the product you want.

**Comment by quentin452** [comment]
fixed in V0.33 by removing carbonization
