### ISSUE TITLE
[1.7.10] Window title and image.

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#355]
[Change window title and image.zip](https://github.com/quentin452/privates-minecraft-modpack/files/10959917/Change.window.title.and.image.zip)

**Comment by quentin452** [comment]
I have it in my modpack but i don't know how to use it

**Comment by GamebP** [comment]
Put config and the file with image and boom you have a new title and a new image not just minecraft logo.

**Comment by quentin452** [comment]
fixed in V0.33 by removing TWD
