### ISSUE TITLE
[1.7.10] Spam log : Failed to send analytics event data. Result of attempt: Connexion refusée (Connection refused)

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#361]
Spam log every 10 seconds when iam in the multiplayer menu

**Comment by quentin452** [comment]
fixed by disabling send analytics in menus

**Comment by CaliforniaDaaan** [comment]
what menu option did you config to disable ga-api?

edit: disregard, if anyone else has this issue setting allow-snooper to false in 
server properties will disable ga-api from sending updates.
