### ISSUE TITLE
[1.12.2]: Unable to plant

### ISSUE THREAD

**Issue by Di0goRocha** [quentin452/1.7.10-Forge-renewed-v1#426]
### Modpack

MysticsMonstrositymodified

### Game log

adawda

### Description

I cant plant seeds / potatos etc because the hoe isnt working on the pack (tryied with wooden and stone one)

**Comment by quentin452** [comment]
Fixed in V6.0modifiedstable11 by disabling Tilling Land Requires Animation in immersive combat
