### ISSUE TITLE
[V0.85.6HOTFIX]: Invisible Starter Chest/gravestone/other tile entities 

### ISSUE THREAD

**Issue by DILLOY** [quentin452/1.7.10-Forge-renewed-v1#435]
### Modpack

Biggess Pack Cat Edition

### Game log

idk what to put here

### Description

Upon launching the pack successfully creating a world with a starter chest, the starter chest seemed invisible, but I could still open it.

**Comment by quentin452** [comment]
fixed in V0.85.61 by downgrading hodgepodge from 2.2.30(my fork) to 2.2.29(the official repo)
