### ISSUE TITLE
[V0.85.62]: Tinkers Missing Textures in Tool Station and Stencil Table blank Patterns 

### ISSUE THREAD

**Issue by DILLOY** [quentin452/1.7.10-Forge-renewed-v1#439]
### Modpack

Biggess Pack Cat Edition

### Game log

no log

### Description

ok in the stencil table, some of the icons don't show what it is it shows a blank stencil plus when entering the tool station I can see some purple, meaning texture is missing or there is a wrong texture path or something I don't know.

here is the tool station screenshot. https://pasteboard.co/t69E8UiyRMO0.png

here is the stencil table texture issue, you can see on the right that stencils are not showing, here 

https://pasteboard.co/FAmkTx3R1Kvy.png

**Comment by quentin452** [comment]
fixed in V0.85.64 by removing tinker defense
