### ISSUE TITLE
[1.7.10]: The Mod Simply Daggers Has Recipe Conflicts With The Mod Chisel 

### ISSUE THREAD

**Issue by DILLOY** [quentin452/1.7.10-Forge-renewed-v1#453]
### Modpack

Biggess Pack Cat Edition V0.85.67

### Game log

no log

### Description

Chisel Recipe https://imgur.com/GzplOdv

Simply Daggers Recipe https://imgur.com/flG92et

**Comment by quentin452** [comment]
fixed in Biggess Pack Cat Edition V0.85.67 by using crafttweaker
