### ISSUE TITLE
[1.7.10]: GwyCraft Missing Textures ""Sandstones + smooth""

### ISSUE THREAD

**Issue by DILLOY** [quentin452/1.7.10-Forge-renewed-v1#454]
### Modpack

Biggess Pack Cat Edition V0.85.67

### Game log

no log

### Description

Seems like all sandstones in GwyCraft are missing textures.

GwyCraft screenshot https://imgur.com/D1AL0cX

**Comment by quentin452** [comment]
fixed in V0.85.70 by hiding blocks with missing textures using crafttweaker
