### ISSUE TITLE
[1.7.10]: Hardcore Ender Expansion , Two Missing Textures  

### ISSUE THREAD

**Issue by DILLOY** [quentin452/1.7.10-Forge-renewed-v1#456]
### Modpack

Biggess Pack Cat Edition V0.85.67

### Game log

no log

### Description

 https://imgur.com/RzDcaUI

https://imgur.com/tIoR190

**Comment by quentin452** [comment]
fixed in V0.85.70 by hiding blocks with missing textures using crafttweaker
