### ISSUE TITLE
SerializationIsBad Server crash

### ISSUE THREAD

**Issue by gengyunmaster** [quentin452/1.7.10-Forge-renewed-v1#470]
### Modpack

BiggessPackCatEdition-0.85.78.3

### Game log

[fml-server-latest.log](https://github.com/quentin452/privates-minecraft-modpack/files/12713573/fml-server-latest.log)

### Description

Server can not start because of using SerializationIsBad without any patch modules configured.

**Comment by HeatherComputer** [comment]
> ### Modpack
> 
> BiggessPackCatEdition-0.85.78.3
> ### Game log
> 
> [fml-server-latest.log](https://github.com/quentin452/privates-minecraft-modpack/files/12713573/fml-server-latest.log)
> ### Description
> 
> Server can not start because of using SerializationIsBad without any patch modules configured.

SerialisationIsBad wasn't able to grab its config file from github.
This looks to be an issue on your machine's end - it failed to resolve the `raw.githubusercontent.com` host - but the text grabbed by the mod can be found [here](https://raw.githubusercontent.com/dogboy21/serializationisbad/master/serializationisbad.json) or downloaded manually from [here](https://github.com/dogboy21/serializationisbad/blob/master/serializationisbad.json)

Sticking the file in your server's dir (next to server.properties iirc) should resolve the crash, but it wouldn't explain why the server was unable to resolve the `raw.githubusercontent.com` domain...



(as for why it crashes, it's done as a safety measure - not having the patches is... *bad*.)

**Comment by quentin452** [comment]
Can you try updating serializationsisbad? https://www.curseforge.com/minecraft/mc-mods/serializationisbad/files/4728250

**Comment by gengyunmaster** [comment]
Yes. New version of SerializationIsBad works fine. Thank you very much!
