### ISSUE TITLE
[1.7.10]: Pocket furnace and pocket workbenct broken

### ISSUE THREAD

**Issue by Bleb1k** [quentin452/1.7.10-Forge-renewed-v1#493]
### Modpack

Biggess pack cat edition V0.86.1.2

### Game log

no logs)

### Description

![pic of pocket furnace and pocket workbench](https://cdn.discordapp.com/attachments/1095191079516635219/1171352886035353600/image.png?ex=655c5e62&is=6549e962&hm=d2bbc860031d268f6e403e07202cf2e45f56bbced2359071ed74ebdeede91f27&)
Pocket workbench works only when you click with it on something, and pocket furnace don't work at all)

**Comment by quentin452** [comment]
infact there is no code in the Pocket Furnace , so its normal that doesn't work :D , so it seem that the mod is not terminated

the mod will be removed in V0.86.1.4
