### ISSUE TITLE
[1.7.10]: Add The Betweenlands mod

### ISSUE THREAD

**Issue by xronin01** [quentin452/1.7.10-Forge-renewed-v1#663]
### Modpack

Biggess Pack Cat Edition

### Description

https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod

**Comment by quentin452** [comment]
Need to patch hodgepodge compat

**Comment by GamebP** [comment]
do it right now

> Need to patch hodgepodge compat

**Comment by quentin452** [comment]
use too much memories
