### ISSUE TITLE
Add Custom Main Menu Mod

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#693]

**Comment by GamebP** [comment]
https://www.curseforge.com/minecraft/mc-mods/custom-main-menu
Config: [CustomMainMenu.zip](https://github.com/quentin452/privates-minecraft-modpack/files/13780935/CustomMainMenu.zip)
File in modpack dir: [resources.zip](https://github.com/quentin452/privates-minecraft-modpack/files/13780948/resources.zip)

**Comment by quentin452** [comment]
your configs are doesn't work (the resources.zip)
