### ISSUE TITLE
[1.7.10]: Add Realistic Brewing Stand mod

### ISSUE THREAD

**Issue by xronin01** [quentin452/1.7.10-Forge-renewed-v1#694]
### Modpack

Biggess Pack Cat Edition

### Description

https://www.curseforge.com/minecraft/mc-mods/realistic-brewing-stand

**Comment by quentin452** [comment]
it seem that another mod had a realistic brewing stand in my modpack

**Comment by xronin01** [comment]
which mod does this?

**Comment by quentin452** [comment]
really idk,but when the mod is enabled i can see two different rendering on the brewing stand
