### ISSUE TITLE
Add Color Blocks + Mod

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#711]

**Comment by GamebP** [comment]
[color_blocks_mod_1.7.10.jar.zip](https://github.com/quentin452/privates-minecraft-modpack/files/13789303/color_blocks_mod_1.7.10.jar.zip)

**Comment by quentin452** [comment]
will probably add Color Block + instead of Color block

https://www.curseforge.com/minecraft/mc-mods/color-blocks-plus/files/2593260

**Comment by GamebP** [comment]
hmm ok why not both change one

**Comment by quentin452** [comment]
Added in V0.94.6
