### ISSUE TITLE
Add Energy Drinks Mod

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#716]

**Comment by GamebP** [comment]
[energy_drinks_mod_1.7.10.jar.zip](https://github.com/quentin452/privates-minecraft-modpack/files/13789336/energy_drinks_mod_1.7.10.jar.zip)

**Comment by quentin452** [comment]
know causing crash server since V0.37specialdedicatedserverpatch
