### ISSUE TITLE
[1.7.10]: Enchiridion2 : json errors

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#904]
### Modpack

Bagges Pack 1.7.10

### Game log

[fix it.txt](https://github.com/quentin452/privates-minecraft-modpack/files/13823083/fix.it.txt)

### Description

?????

**Comment by quentin452** [comment]
Fixed in V0.94.83 by Making a fork of Enchiridion2 (and ignoring json errors ,cause no issue ingame)
