### ISSUE TITLE
[1.7.10]: Add Tinkers-Defense GTNH fork mod

### ISSUE THREAD

**Issue by xronin01** [quentin452/1.7.10-Forge-renewed-v1#918]
### Modpack

Biggess Pack Cat Edition

### Description

https://github.com/GTNewHorizons/Tinkers-Defense

**Comment by quentin452** [comment]
require https://github.com/quentin452/privates-minecraft-modpack/issues/792

**Comment by quentin452** [comment]
Added in V0.95.6
