### ISSUE TITLE
(1.7.10) Bug with displaying vanilla mobs on server (player)

### ISSUE THREAD

**Issue by KempeR0744** [quentin452/1.7.10-Forge-renewed-v1#920]
### Modpack

Custom build

### Game log

none

### Description

Hi everyone, I'm writing here for the first time, so don't kick me :).
In general, after installing the mod Endlessids, and adding 3 necessary mods or libraries. then I all very long customized and sorted id biomes. all worked. but the matter is not in this: when entering the server (when the player is on the server, example friend) - him do not display all the mobs from vanilla minecraft. but display all the mobs from other mods. but in the game (being in singleplayer) all correctly displayed.
Help me solve this problem!
p.s. variants with the selection of mods excluded, as I have installed 201 mods. and everything worked well, except for biomes. so I wanted to solve this problem to play at all 200%. in crash reports also gives little ... except for the developer console...which I haven't looked at. but I don't think there will be anything there.

### Participant edits
- [ ] I haven't tried removing mods one by one.

**Comment by GamebP** [comment]
~Is it your modpack or it is https://legacy.curseforge.com/minecraft/modpacks/biggess-pack-cat-edition ?~
### Edit
I see it's a custom modpack. 
But custom modpacks with some unknown/known mods have incompatibilities. Maybe thats why it's coused.
Have you tried removing mods 1 by 1?

**Comment by KempeR0744** [comment]
No haven't tried it, as all mods work perfectly and glitch free. without that mod. I think there is an id conflict somewhere.

**Comment by quentin452** [comment]
try switching to the ConfigHelper Entity id extender and disabling Endlessids entity id extender in config 

add these mods : 

-https://www.curseforge.com/minecraft/mc-mods/evilnotchlib

-https://github.com/quentin452/confighelper2

**Comment by KempeR0744** [comment]
this mod works on version 1.12.2... I have 1.7.10.
 
but thanks for the tip about expanding the mob indifiers

**Comment by quentin452** [comment]
> this mod works on version 1.12.2... I have 1.7.10.
> 
> but thanks for the tip about expanding the mob indifiers

confighelper/evilnotchlib has an 1.7 version :D

**Comment by KempeR0744** [comment]
and tell me how to import it into my build? It is on version 1.12.2. it is desirable to be more detailed. as I am very poorly oriented on this site.

**Comment by quentin452** [comment]
i use these mods into my modpack.....

**Comment by quentin452** [comment]
https://github.com/quentin452/confighelper2/releases/tag/1.2.5.5
https://www.curseforge.com/minecraft/mc-mods/evilnotchlib/files/2882525

**Comment by KempeR0744** [comment]
Thanks, but how to disable the extension of mob indifiers in the mod or endlessids config

**Comment by quentin452** [comment]
disable extendEntity

**Comment by KempeR0744** [comment]
thank

**Comment by KempeR0744** [comment]
As I understand it, to cure the problem, you need to add 2 mods? That you sent me?

**Comment by quentin452** [comment]
> As I understand it, to cure the problem, you need to add 2 mods? That you sent me?

to potentially fix the problem , you need to add these two mods and disabling entity ids extender from endlessids

**Comment by quentin452** [comment]
do you had the mod pixelmon in your pack?

**Comment by KempeR0744** [comment]
No. I have the max techno-magic build.

**Comment by KempeR0744** [comment]
and evilnotchlib download, that has 95k downloads?

**Comment by KempeR0744** [comment]
Oh, I get it, there's a separate version on the left side of the column.

**Comment by KempeR0744** [comment]
I disabled entity id extender and installed evilnotchlib and everything worked. thanks a lot.
p.s with confighelper2 the build crashes, but it's nothing. the most important thing is now all vanilla mobs are displayed to the player.

**Comment by quentin452** [comment]
so probably the issue should be reported to endlessids github

**Comment by KempeR0744** [comment]
How?

**Comment by quentin452** [comment]
if you had problems with confighelper crashes , you could use configurations from Biggess Pack Cat Edition :

**Comment by quentin452** [comment]
> How?

i mean the vanilla mob not get displayed on server should be reported to endlessids github https://github.com/GTMEGA/EndlessIDs/issues

**Comment by KempeR0744** [comment]
understand, thank
